// ici une fake bdd pour simplifier l'utilisation de data en dur
export default [
  {
    id: 1,
    title: '#01 Nos Cinq Terres',
    src: '5 terre.jpg',
    alt: 'description du tableaux à l&#39huile : une vue des 5 terre en italie , entre mer et terre , entre habitation atypique et rocher naturel.',
    description: 'La valeur de Nos Cinq Terres est de 900€ pour une mesure de 60 x 73',
    slug: '5-terre',
    audio: 'hang01.mp3',
    classname: 'cinq-terres',
  },
  {
    id: 2,
    title: '#02 Fraîcheur Chaude',
    src: 'ananas.jpg',
    alt: 'description du tableaux à l&#39huile : un ananas en gros plan , l&#39effet sur la toile a été vieilli . les couleurs bleu et verte sont dominantes',
    description: 'La valeur de Fraîcheur Chaude est de 360€ pour une mesure de 46 x 33',
    slug: 'ananas',
    audio: 'guitare.mp4',
    classname: 'ananas',
  },
  {
    id: 3,
    title: '#03 Big Bang Flower',
    src: 'big bang flower.jpg',
    alt: 'description du tableau à l&#39huile : un œuvre abstraite , qui fait penser à une explosion de pétale de fleur pointus.',
    description: 'La valeur de big bang flower est de 1350€ pour une mesure de 73 x 92',
    slug: 'big-bang-flower',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 4,
    title: '#04 Charge Bleuté ',
    src: 'bouc.jpg',
    alt: 'description du tableau à l&#39huile:la tête d&#39un bélier bleu dont le corp disparait sur des nuances de blanc.',
    description: 'La valeur de Charge Bleuté est de 900€ pour une mesure de 60 x 60',
    slug: 'bouc',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'bouc',
  },

  {
    id: 5,
    title: '#05 Explosion Native',
    src: 'boum.jpg',
    alt: 'description du tableau à l&#39huile : un œuvre abstraite , qui fait penser à une explosion de pétale de fleur dans différents tons.',
    description: 'La valeur de Explosion Native est de 1350€ pour une mesure de 80 x 80',
    slug: 'boum',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'boum',
  },

  {
    id: 6,
    title: '#06 Montée Figuière',
    src: 'agave.jpg',
    alt: 'description du tableau à l&#39huile : un groupe de figues montant vers un ciel bleu.',
    description: 'La valeur de Montée Figuière est de 450€ pour une mesure de 56 x 38',
    slug: 'agave',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'cactus',
  },

  {
    id: 7,
    title: '#07 Cachette...',
    src: 'feuille.jpg',
    alt: 'description du tableau à l&#39huile : des feuille figés au sol , de multiple couleurs vive tel que le rouge et le vert.',
    description: 'Le prix de Cachette est de 360€ pour une mesure de 40 x 40',
    slug: 'feuilles',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'feuilles',
  },

  {
    id: 8,
    title: '#08 Rêverie',
    src: 'lac et bambou.jpg',
    alt: 'description du tableau à l&#39huile : un étang calme et serein au couleurs vertes et bleus arborants des bambou parsemés',
    description: 'La valeur de Rêverie est de 540€ pour une mesure de 61 x 50',
    slug: 'sticks',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'lac-et-lotus',
  },

  {
    id: 9,
    title: '#09 Silence de Paix',
    src: 'le sage.jpg',
    alt: 'description du tableau à l&#39huile : un sage voilé sur fond blanc arborant une tunique blanche nous faisant un signe de main',
    description: 'La valeur de Silence de Paix est de 360€ pour une mesure de 40 x 50',
    slug: 'pause',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'le-sage',
  },

  {
    id: 10,
    title: '#10 Danse des Agaves',
    src: 'nénuphar.jpg',
    alt: 'description du tableau à l&#39huile : un nénuphar aux somptueuses couleurs bleu et violet s&#39ouvrant lentement',
    description: 'La valeur de Danse des Agaves est de 1125€ pour une mesure de 60 x 81',
    slug: 'Partition',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'lotus',
  },

  {
    id: 11,
    title: '#11 Profondeur des Ombres',
    src: 'meduse.jpg',
    alt: 'description du tableau à l &#39huile : plusieur méduses partant du fond noir des océans pour rejoindre la surface',
    description: 'La valeur de Profondeur des Ombres est de 1800€ pour une mesure de 60 x 120',
    slug: 'chorale',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'meduse',
  },

  {
    id: 12,
    title: '#12 Cloches Neigeuses',
    src: 'mouton 2.jpg',
    alt: 'description du tableau à l&#39huile : un troupeau de mouton au loin , dans les ton clair qui se confonde avec l&#39horizon et le ciel',
    description: 'La valeur de Cloches Neigeuse est de 1350€ pour une mesure de 50 x 100',
    slug: 'Cacophonie',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'mouton',
  },

  {
    id: 13,
    title: '#13 Printemp des Montagnes',
    src: 'mouton.jpg',
    alt: 'description du tableau à l &#39huile : les moutons en rang avançant avec leur berger. un homme discret avec chapeau et bâton',
    description: 'La valeur de Printemp des Montagnes est de 1800€ pour une mesure de 80 x 99',
    slug: 'berçeuse',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'mouton-2',
  },

  {
    id: 14,
    title: '#14 Immobilité du Mouvement',
    src: 'poisson rouge.jpg',
    alt: 'description du tableau à l&#39huile :un poisson rouge immense, presque figé face à nous dans une eau agitée',
    description: 'La valeur de Immobilité du Mouvement est de 1350€ pour une mesure de 80 x 80',
    slug: 'silence',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'poisson-rouge',
  },

  {
    id: 15,
    title: '#15 Une fois ici...',
    src: 'venise.jpg',
    alt: 'description du tableau à l&#39huile : une vue calme de venise , sur l&#39eau entre des maisons silencieuses',
    description: 'La valeur de Une fois ici est de 3600€ pour une mesure de 100 x 150',
    slug: 'ballade',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'venise',
  },

  {
    id: 16,
    title: '#16 Montmartre',
    src: 'village.jpg',
    alt: 'description du tableau à l&#39huile : une vue de montmartre dans des tons très clairs',
    description: 'La valeur de Montmartre est de 540€ pour une mesure de 30 x 60',
    slug: 'crescendo',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'village',
  },
  {
    id: 17,
    title: '#17 Partons pour voir...',
    src: 'bateau.jpg',
    alt: 'description du tableau à l&#39huile : un bateau prenant de la distance en partant des Cinq Terres',
    description: 'La valeur de Partons pour voir est de 2250€ pour une mesure de 116 x 89',
    slug: 'Demi-soupir',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'bateau',
  },
  {
    id: 18,
    title: '#18 Liberté Simple',
    src: 'petite.jpg',
    alt: 'description du tableau à l&#39huile : une petite fille faisant le signe deux avec ces doigt comme pour demander deux dollars',
    description: 'La valeur de Liberté Simple est de 1800€ pour une mesure de 60 x 120',
    slug: 'Balance',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'petite',
  },
  {
    id: 19,
    title: '#19 Axes émotions',
    src: 'tiges.jpg',
    alt: 'description du tableau à l&#39huile : bambou plan proche coloré',
    description: 'La valeur de Axes émotions est de 1800€ pour une mesure de 100 x 80',
    slug: 'sticks',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'tiges',
  },
  {
    id: 20,
    title: '#20 Temps Anciens',
    src: 'vase.jpg',
    alt: 'description du tableau à l&#39huile : une vue de montmartre dans des tons très clairs',
    description: 'La valeur de Temps Anciens est de 1800€ pour une mesure de 60 x 120',
    slug: 'Tessiture',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'vase',
  },
  {
    id: 21,
    title: '#21 Sacs des infinis',
    src: 'peinture.jpg',
    alt: 'description du tableau à l&#39huile : petits sacs de poudre colorés',
    description: 'La valeur de Sacs des infinis est de 360€ pour une mesure de 40 x 40',
    slug: '??',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'peinture',
  },

  {
    id: 22,
    title: '#23 Embouchure',
    src: 'couleurs.jpg',
    alt: 'description du tableau à l&#39huile : ensemble de bouteille très colorés',
    description: 'La valeur de Embouchure est de 360€ pour une mesure de 46 x 38',
    slug: 'Embouchure',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'couleurs',
  },
];
