// ici une fake bdd pour simplifier l'utilisation de data en dur
export default [
  {
    id: 1,
    title: '#01 Demi-pause',
    src: '5 terre.jpg',
    alt: 'description du tableaux à l&#39huile : une vue des 5 terre en italie , entre mer et terre , entre habitation atypique et rocher naturel.',
    description: 'La valeur de Demi-pause est de 900€ pour une mesure de 60 x 73',
    slug: '5-terre',
    audio: 'hang01.mp3',
    classname: 'cinq-terres',
  },
  {
    id: 2,
    title: '#02 Tempo',
    src: 'ananas.jpg',
    alt: 'description du tableaux à l&#39huile : un ananas en gros plan , l&#39effet sur la toile a été vieilli . les couleurs bleu et verte sont dominantes',
    description: 'La valeur du Tempo est de 360€ pour une mesure de 46 x 33',
    slug: 'ananas',
    audio: 'guitare.mp4',
    classname: 'ananas',
  },
  {
    id: 3,
    title: '#03 Symphonie',
    src: 'big bang flower.jpg',
    alt: 'description du tableau à l&#39huile : un œuvre abstraite , qui fait penser à une explosion de pétale de fleur pointus.',
    description: 'La valeur de Symphonie est de 1350€ pour une mesure de 73 x 92',
    slug: 'big-bang-flower',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 4,
    title: '#04 Piston ',
    src: 'bouc.jpg',
    alt: 'description du tableau à l&#39huile:la tête d&#39un bélier bleu dont le corp disparait sur des nuances de blanc.',
    description: 'La valeur de Piston est de 900€ pour une mesure de 60 x 60',
    slug: 'bouc',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'bouc',
  },

  {
    id: 5,
    title: '#05 Polyphonie',
    src: 'boum.jpg',
    alt: 'description du tableau à l&#39huile : un œuvre abstraite , qui fait penser à une explosion de pétale de fleur dans différents tons.',
    description: 'La valeur de Polyphonie est de 1350€ pour une mesure de 80 x 80',
    slug: 'boum',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'boum',
  },

  {
    id: 6,
    title: '#06 Choeurs',
    src: 'agave.jpg',
    alt: 'description du tableau à l&#39huile : un groupe d&#39agaves montant vers un ciel bleu.',
    description: 'La valeur de Choeur est de 1125€ pour une mesure de 60 x 81',
    slug: 'agave',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'cactus',
  },

  {
    id: 7,
    title: '#07 Répertoire',
    src: 'feuille.jpg',
    alt: 'description du tableau à l&#39huile : des feuille figés au sol , de multiple couleurs vive tel que le rouge et le vert.',
    description: 'Le prix du Tempo est de 360€ pour une mesure de 40 x 40',
    slug: 'feuilles',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'feuilles',
  },

  {
    id: 8,
    title: '#08 Sticks',
    src: 'lac et bambou.jpg',
    alt: 'description du tableau à l&#39huile : un étang calme et serein au couleurs vertes et bleus arborants des bambou parsemés',
    description: 'La valeur de Sticks est de 1800€ pour une mesure de 100 x 80',
    slug: 'sticks',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 9,
    title: '#09 Pause',
    src: 'le sage.jpg',
    alt: 'description du tableau à l&#39huile : un sage voilé sur fond blanc arborant une tunique blanche nous faisant un signe de main',
    description: 'La valeur de Pause est de 1800€ pour une mesure de 60 x 120',
    slug: 'pause',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 10,
    title: '#10 Partition',
    src: 'nénuphar.jpg',
    alt: 'description du tableau à l&#39huile : un nénuphar aux somptueuses couleurs bleu et violet s&#39ouvrant lentement',
    description: 'La valeur de Partition est de 360€ pour une mesure de 46 x 33',
    slug: 'Partition',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 11,
    title: '#11 Chorale',
    src: 'meduse.jpg',
    alt: 'description du tableau à l &#39huile : plusieur méduses partant du fond noir des océans pour rejoindre la surface',
    description: 'La valeur de Chorale est de 1800€ pour une mesure de 60 x 120',
    slug: 'chorale',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 12,
    title: '#12 Cacophonie',
    src: 'mouton 2.jpg',
    alt: 'description du tableau à l&#39huile : un troupeau de mouton au loin , dans les ton clair qui se confonde avec l&#39horizon et le ciel',
    description: 'La valeur de Cacophonie est de 1350€ pour une mesure de 50 x 100',
    slug: 'Cacophonie',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 13,
    title: '#13 Berçeuse',
    src: 'mouton.jpg',
    alt: 'description du tableau à l &#39huile : les moutons en rang avançant avec leur berger. un homme discret avec chapeau et bâton',
    description: 'La valeur de Berçeuse est de 1800€ pour une mesure de 80 x 99',
    slug: 'berçeuse',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 14,
    title: '#14 Silence',
    src: 'poisson rouge.jpg',
    alt: 'description du tableau à l&#39huile :un poisson rouge immense, presque figé face à nous dans une eau agitée',
    description: 'La valeur de Silence est de 1350€ pour une mesure de 80 x 80',
    slug: 'silence',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 15,
    title: '#15 Ballade',
    src: 'venise.jpg',
    alt: 'description du tableau à l&#39huile : une vue calme de venise , sur l&#39eau entre des maisons silencieuses',
    description: 'La valeur de Ballade est de 3600€ pour une mesure de 100 x 150',
    slug: 'ballade',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },

  {
    id: 16,
    title: '#16 Crescendo',
    src: 'village.jpg',
    alt: 'description du tableau à l&#39huile : une vue de montmartre dans des tons très clairs',
    description: 'La valeur de Crescendo est de 540€ pour une mesure de 30 x 60',
    slug: 'crescendo',
    audio: 'asudhfasdfudshf.mp4',
    classname: 'big-bang-flower',
  },
];
